# Generated by Django 5.0.1 on 2024-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='img',
            field=models.ImageField(default=1, upload_to='cat_icon'),
            preserve_default=False,
        ),
    ]
